import "./import-tests.js";
import "./export-tests.js";
import "./setter-tests.js";
import "./misc-tests.js";
import "./compiler-tests.js";
import "./output-tests.js";
import "./transform-tests.js";
import "./babel-plugin-tests.js";
import "./repl-tests.js";
