/* eslint-disable sort-keys */
const COMPILER = {
  SOURCE_TYPE_SCRIPT: 1,
  SOURCE_TYPE_MODULE: 2,
  SOURCE_TYPE_UNAMBIGUOUS: 3,
  SOURCE_TYPE_JSON: 4,
  SOURCE_TYPE_WASM: 5,
  TRANSFORMS_CONSOLE: 1,
  TRANSFORMS_DYNAMIC_IMPORT: 2,
  TRANSFORMS_EXPORT: 4,
  TRANSFORMS_EVAL: 8,
  TRANSFORMS_IMPORT: 16,
  TRANSFORMS_IMPORT_META: 32,
  TRANSFORMS_REFLECT: 64,
  TRANSFORMS_TEMPORALS: 128,
  TRANSFORMS_UNDECLARED: 256
}

export default COMPILER
