/* eslint-disable sort-keys */
const ENTRY = {
  ERROR_GETTER: {},
  ERROR_STAR: {},
  GETTER_TYPE_DEFAULT: 1,
  GETTER_TYPE_STAR_CONFLICT: 2,
  INITIAL_VALUE: {},
  LOAD_INDETERMINATE: -1,
  LOAD_INCOMPLETE: 0,
  LOAD_COMPLETED: 1,
  NAMESPACE_FINALIZATION_DEFERRED: -1,
  NAMESPACE_FINALIZATION_INCOMPLETE: 0,
  NAMESPACE_FINALIZATION_COMPLETED: 1,
  SETTER_TYPE_DEFAULT: 1,
  SETTER_TYPE_DYNAMIC_IMPORT: 2,
  SETTER_TYPE_EXPORT_FROM: 3,
  SETTER_TYPE_NAMESPACE: 4,
  STATE_INITIAL: 0,
  STATE_PARSING_STARTED: 1,
  STATE_PARSING_COMPLETED: 2,
  STATE_EXECUTION_STARTED: 3,
  STATE_EXECUTION_COMPLETED: 4,
  TYPE_CJS: 1,
  TYPE_PSEUDO: 2,
  TYPE_ESM: 3,
  TYPE_JSON: 4,
  TYPE_WASM: 5,
  UPDATE_TYPE_DEFAULT: 1,
  UPDATE_TYPE_LIVE: 2,
  UPDATE_TYPE_INIT: 3
}

export default ENTRY
