import "./acorn/src/expression.js"
import "./acorn/src/location.js"
import "./acorn/src/lval.js"
import "./acorn/src/node.js"
import "./acorn/src/scope.js"
import "./acorn/src/statement.js"
import "./acorn/src/tokencontext.js"
import "./acorn/src/tokenize.js"

export { Parser as default } from "./acorn/src/state.js"
